main3: main3.c
	gcc `pkg-config --cflags --libs gtk+-3.0` -o main3 main3.c -Wall
#	gcc `pkg-config --cflags gtk-3.0` -o main3 main3.c -Wall\
# `pkg-config --libs gtk-3.0`
#	gcc `pkg-config --cflags gtk+-3.0` main3.c -o amin3 `pkg-config --libs gtk+-3.0`
